# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-20 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20190619_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic_path',
            new_name='profile_pic',
        ),
    ]
