# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20190620_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, related_name='profile_followers', to='instagram.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=0, related_name='profile_following', to='instagram.Profile'),
        ),
    ]
